/**
 * @file build-ts.mjs
 * @description Enhanced build pipeline with explicit Source Map generation and minification support.
 * @author Generated by DocExpert
 */

import swc from '@swc/core';
import { glob } from 'glob';
import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * Executes the TypeScript to JavaScript compilation pipeline.
 * Explicitly handles the generation of .js.map files alongside transpiled code.
 * * @async
 * @function executeBuild
 * @returns {Promise<void>}
 */
async function executeBuild() {
    const SOURCE_PATTERN = 'src/asset/ts/**/*.ts';
    const SOURCE_ROOT = 'src/asset/ts';
    const OUTPUT_BASE_DIRECTORY = 'src/asset/js';

    try {
        const sourceFiles = await glob(SOURCE_PATTERN);

        const transformationPromises = sourceFiles.map(async (filePath) => {
            const relativeFilePath = path.relative(SOURCE_ROOT, filePath);
            const destinationPath = path.join(OUTPUT_BASE_DIRECTORY, relativeFilePath).replace(/\.ts$/, '.js');
            const mapPath = `${destinationPath}.map`;

            const sourceContent = await fs.readFile(filePath, 'utf8');

            // Destructuring both 'code' and 'map' from the SWC transformation
            const { code: transformedCode, map: sourceMap } = await swc.transform(sourceContent, {
                filename: filePath,
                sourceMaps: true,
                minify: true, // Enabled minification as requested
                jsc: {
                    parser: {
                        syntax: "typescript",
                        tsx: false,
                        decorators: true
                    },
                    target: "es2022",
                    minify: {
                        compress: true,
                        mangle: true
                    }
                },
                module: {
                    type: "es6"
                }
            });

            await fs.mkdir(path.dirname(destinationPath), { recursive: true });

            // Writing the JavaScript file and the corresponding Source Map file
            const writeOperations = [
                fs.writeFile(destinationPath, transformedCode)
            ];

            if (sourceMap) {
                // Appending the source mapping URL to the bottom of the JS file
                const codeWithMapUrl = `${transformedCode}\n//# sourceMappingURL=${path.basename(mapPath)}`;
                writeOperations[0] = fs.writeFile(destinationPath, codeWithMapUrl);
                writeOperations.push(fs.writeFile(mapPath, sourceMap));
            }

            await Promise.all(writeOperations);
        });

        await Promise.all(transformationPromises);
        console.log('Build completed successfully with Source Maps.');

    } catch (error) {
        console.error('Critical build error:', error);
        process.exit(1);
    }
}

executeBuild();